#ifndef AXS1CONTROLTABLEMACROS_H
#define AXS1CONTROLTABLEMACROS_H

// Control table addresses
#define AXS1_MODEL_NUMBER_L 0
#define AXS1_MODEL_NUMBER_H 1
#define AXS1_FIRMWARE_VERSION 2
#define AXS1_ID 3
#define AXS1_BAUD_RATE 4
#define AXS1_RETURN_DELAY_TIME 5
#define AXS1_STATUS_RETURN_LEVEL 16
#define AXS1_IR_LEFT_FIRE_DATA 26
#define AXS1_IR_CENTRE_FIRE_DATA 27
#define AXS1_IR_RIGHT_FIRE_DATA 28
#define AXS1_LIGHT_LEFT_DATA 29
#define AXS1_LIGHT_CENTRE_DATA 30
#define AXS1_LIGHT_RIGHT_DATA 31
#define AXS1_IR_OBSTACLE_DETECTED 32
#define AXS1_LIGHT_DETECTED 33
#define AXS1_SOUND_DATA 35
#define AXS1_SOUND_DATA_MAX_HOLD 36
#define AXS1_SOUND_DETECTED_COUNT 37
#define AXS1_SOUND_DETECTED_TIME_L 38
#define AXS1_SOUND_DETECTED_TIME_H 39
#define AXS1_BUZZER_NOTES 40
#define AXS1_BUZZER_RINGING_TIME 41
#define AXS1_REGISTERED 44
#define AXS1_IR_REMOCON_ARRIVED 46
#define AXS1_LOCK 47
#define AXS1_REMOCON_RX_DATA_L 48
#define AXS1_REMOCON_RX_DATA_H 49
#define AXS1_REMOCON_TX_DATA_L 50
#define AXS1_REMOCON_TX_DATA_H 51
#define AXS1_IR_OBSTACLE_DETECT_COMPARE_RD 52
#define AXS1_LIGHT_DETECT_COMPARE_RD 53

#endif // AXS1CONTROLTABLEMACROS_H
